package com.it3030.paf.smartcampus.domain.enums;

public enum NotificationType {
  BOOKING_REQUEST_SUBMITTED,
  BOOKING_APPROVAL_REQUIRED,
  BOOKING_APPROVED,
  BOOKING_REJECTED,
  TICKET_CREATED,
  TICKET_ADMIN_REPLY,
  TICKET_STUDENT_REPLY,
  TICKET_RESOLVED,
  TICKET_CLOSED,
  SYSTEM
}
